services:
  package:
    container_name: nestjs-mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    ports:
      - 3000:3000
      - 9229:9229
      - 6277:6277
    environment:
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/package
      - node_modules:/package/node_modules

volumes:
  node_modules:
    name: nestjs-mcp-node-modules
